use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedTestCase {
    pub name: String,
    pub description: String,
    pub function: String,
    pub test_type: String,
    #[serde(default)]
    pub input_data: Vec<GeneratedInput>,
    #[serde(default)]
    pub expected_behavior: String,
    #[serde(default)]
    pub security_checks: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct GeneratedInput {
    pub name: String,
    pub value: String,
    pub rust_type: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TestGenerationResult {
    pub source: String,
    pub cases: Vec<GeneratedTestCase>,
    pub output_path: Option<String>,
}

pub fn generate_from_source(source_path: &Path) -> Result<TestGenerationResult> {
    let content = fs::read_to_string(source_path)
        .with_context(|| format!("Failed to read {}", source_path.display()))?;
    let functions = extract_public_functions(&content);
    let source = source_path.to_string_lossy().to_string();

    let mut cases = Vec::new();
    for function in &functions {
        let signature = function_signature(&content, function);
        let inputs = generate_input_data(&signature);
        let mut add_case = |suffix: &str,
                            test_type: &str,
                            description: &str,
                            expected_behavior: &str,
                            security_checks: Vec<String>| {
            cases.push(GeneratedTestCase {
                name: format!("test_{}_{}", function, suffix),
                description: description.replace("{function}", function),
                function: function.clone(),
                test_type: test_type.into(),
                input_data: inputs.clone(),
                expected_behavior: expected_behavior.into(),
                security_checks,
            });
        };

        add_case(
            "happy_path",
            "happy_path",
            "Normal operation test for {function}",
            "The entry point accepts valid inputs and produces its documented normal result.",
            vec![],
        );
        add_case(
            "error_conditions",
            "error_condition",
            "Error condition test for {function}",
            "Invalid or rejected input must fail without changing protected state.",
            vec!["assert unauthorized callers are rejected".into()],
        );
        add_case(
            "boundary_conditions",
            "boundary_condition",
            "Boundary condition test for {function}",
            "Minimum, maximum, zero, and empty values are handled explicitly.",
            vec![],
        );
        add_case(
            "security",
            "security",
            "Security scenario test for {function}",
            "Authorization, state isolation, and replay protection are verified.",
            vec![
                "verify authorization is required for protected operations".into(),
                "verify failed authorization does not mutate state".into(),
                "verify repeated calls cannot bypass validation".into(),
            ],
        );
    }

    Ok(TestGenerationResult {
        source,
        cases,
        output_path: None,
    })
}

pub fn write_generated_tests(result: &TestGenerationResult, output_path: &Path) -> Result<()> {
    let mut code = String::from(
        "// Generated by StarForge. Review contract-specific assertions before committing.\n\n",
    );

    for case in &result.cases {
        code.push_str(&format!(
            "/// {}\n#[test]\nfn {}() {{\n    let scenario = {:?};\n    let function = {:?};\n    let expected_behavior = {:?};\n    assert!(!scenario.is_empty());\n    assert!(!function.is_empty());\n    assert!(!expected_behavior.is_empty());\n",
            case.description, case.name, case.test_type, case.function, case.expected_behavior
        ));
        for input in &case.input_data {
            code.push_str(&format!(
                "    let {}: &str = {:?};\n    assert!(!{}.is_empty());\n",
                safe_identifier(&input.name), input.value, safe_identifier(&input.name)
            ));
        }
        for check in &case.security_checks {
            code.push_str(&format!("    // Security check: {}\n", check));
        }
        code.push_str("}\n\n");
    }

    fs::write(output_path, code)
        .with_context(|| format!("Failed to write {}", output_path.display()))?;
    Ok(())
}

fn extract_public_functions(content: &str) -> Vec<String> {
    content
        .lines()
        .filter_map(|line| {
            let trimmed = line.trim();
            let rest = trimmed.strip_prefix("pub fn ")?;
            rest.split('(').next().map(|name| name.trim().to_string())
        })
        .collect()
}

fn function_signature(content: &str, function: &str) -> String {
    content
        .lines()
        .find(|line| line.trim_start().starts_with(&format!("pub fn {}(", function)))
        .unwrap_or_default()
        .trim()
        .to_string()
}

fn generate_input_data(signature: &str) -> Vec<GeneratedInput> {
    let Some(parameters) = signature.split_once('(').and_then(|(_, rest)| rest.split_once(')'))
    else {
        return Vec::new();
    };

    parameters
        .0
        .split(',')
        .filter_map(|parameter| {
            let (name, rust_type) = parameter.split_once(':')?;
            let name = name.trim().trim_start_matches("mut ").trim();
            if name == "env" || name.is_empty() {
                return None;
            }
            let rust_type = rust_type.trim().to_string();
            Some(GeneratedInput {
                name: safe_identifier(name),
                value: sample_value(&rust_type),
                rust_type,
            })
        })
        .collect()
}

fn sample_value(rust_type: &str) -> String {
    let normalized = rust_type.replace(' ', "");
    match normalized.as_str() {
        "bool" => "true".into(),
        "u32" | "u64" | "i32" | "i64" => "1".into(),
        "Address" => "generated_test_address()".into(),
        "String" | "soroban_sdk::String" => "valid-input".into(),
        _ => "generated-input".into(),
    }
}

fn safe_identifier(value: &str) -> String {
    let mut identifier = value
        .chars()
        .map(|character| {
            if character.is_ascii_alphanumeric() || character == '_' {
                character
            } else {
                '_'
            }
        })
        .collect::<String>();
    if identifier.is_empty() || identifier.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        identifier.insert(0, '_');
    }
    identifier
}

fn is_mutating(content: &str, func: &str) -> bool {
    let mut in_fn = false;
    for line in content.lines() {
        if line.contains(&format!("pub fn {}", func)) {
            in_fn = true;
        }
        if in_fn {
            if line.contains(".set(") || line.contains("transfer") || line.contains("mint") {
                return true;
            }
            if line.starts_with("pub fn ") && !line.contains(func) {
                break;
            }
        }
    }
    false
}
